name: release
on:
  push:
    branches:
      - main

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish java artifact with gradle
        run: |
          ./gradlew publishAndReleaseToMavenCentral \
            --parallel \
            --continue \
            -PmavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }} \
            -PmavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }} \
            -PsigningInMemoryKey=${{ secrets.SIGNING_KEY }} \
            -PsigningInMemoryKeyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}


  publish-spring:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.native.enabled=false \
            -Pimage.registry.publish.username=${{github.actor}} \
            -Pimage.registry.publish.password=${{secrets.GITHUB_TOKEN}} \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-latest, spring-{VERSION} \
            -Pimage.push=true

  publish-spring-native:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - uses: gradle/actions/setup-gradle@v3
        name: setup gradle

      - name: build and publish Container Image with gradle
        run: |
          ./gradlew :spring-application:buildImage \
            --parallel \
            --continue \
            -Pimage.registry.publish.username=${{github.actor}} \
            -Pimage.registry.publish.password=${{secrets.GITHUB_TOKEN}} \
            -Pimage.name=ghcr.io/tronto20/kitiler \
            -Pimage.tags=spring-native-latest, spring-native-{VERSION}, latest, {VERSION} \
            -Pimage.push=true
